### ISSUE TITLE
include name of original buffer in new buffer name

### ISSUE THREAD

**Issue by articuluxe** [kensanata/in-memory-diff#1]
Neat package.  It would be easier to keep track of which buffer is which if the in-memory-diff buffers were named to correspond to the original buffer they represent.

**Comment by kensanata** [comment]
Yeah, that’s true. Do you want to submit a patch?

**Comment by articuluxe** [comment]
Yes, I can do that.

**Comment by kensanata** [comment]
Thanks. Don’t forget to add your copyright line at the top.

**Comment by kensanata** [comment]
Thanks.
